spring:
#  数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    userName : root
    password : 123456
    url : jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql : true
#    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.253.5
    port: 6379

server:
  servlet:
    context-path: /sell


wechat:
   mpAppId: wx30f36c2b87e997c5
   mpAppSecret: 1e0d6e8475ba4aafaba2aef958ac1302

#后台服务内网穿透地址
project-url:
    wechatMpAuthorize: http://myfood.natapp1.cc
    wechatOpenAuthorize: http://myfood.natapp1.cc
    sell: http://myfood.natapp1.cc




